version: "3.8"
name: test-deploy #fixme: remove name
services:
    db:
        image: postgres:16
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
            POSTGRES_USER: odoo
            POSTGRES_DB: postgres
        ports:
            - "15432:5432"
        volumes:
            - postgresql-data:/var/lib/postgresql/data
            - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
        command: -c 'config_file=/etc/postgresql/postgresql.conf'
        networks:
            - backend
        restart: always
        secrets:
            - postgres_password

    odoo17:
        image: xmars/xmars4:odoo-cicd-github-action
        depends_on:
            - db
        environment:
            PASSWORD_FILE: /run/secrets/postgres_password
            HOST: db
            PORT: 5432
            USER: odoo

        ports:
            - "18069:8069"
            - "18072:8072"
        volumes:
            - ../:/mnt/custom-addons # customize addons
            - ./etc:/etc/odoo
            - ./logs:/var/log/odoo
            - odoo-data:/var/lib/odoo
        networks:
            - frontend
            - backend
        restart: always
        secrets:
            - postgres_password

    # nginx:
    #     image: nginx
    #     depends_on:
    #         - odoo17
    #     volumes:
    #         - ./nginx:/etc/nginx/conf.d
    #     ports:
    #         - "80:80"
    #     networks:
    #         - frontend
#fixme: reupdate config and port
secrets:
    postgres_password:
        file: ./postgresql/password.txt

volumes:
    odoo-data:
    postgresql-data:

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
