name: ci/cd
on:
    pull_request:
        branches: [extrinsic]
        types: [reopened, opened, synchronize, ready_for_review, closed]

jobs:
    dispatch_workflow_test:
        if: github.event.action != 'closed'
        runs-on: ubuntu-latest
        steps:
            - run: gh workflow run manual_cicd.yml --repo xmars4/odoo-cicd-executor -f repo=${{ github.repository }} -f source_branch=${{ github.event.pull_request.head.ref }} -f target_branch=${{github.event.pull_request.base.ref}} -f action=test
        env:
            GH_TOKEN: ${{ secrets.DISPATCH_WORKFLOW_PAT }}

    dispatch_workflow_deploy:
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - run: gh workflow run manual_cicd.yml --repo xmars4/odoo-cicd-executor -f repo=${{ github.repository }} -f source_branch=${{ github.event.pull_request.head.ref }} -f target_branch=${{github.event.pull_request.base.ref}} -f action=deploy
        env:
            GH_TOKEN: ${{ secrets.DISPATCH_WORKFLOW_PAT }}
