name: ci/cd
on:
    pull_request:
        branches: [extrinsic]
        types: [reopened, opened, synchronize, ready_for_review, closed]

env:
    # cicd executor repo info
    REPO: "xmars4/odoo-cicd-executor"
    LOCAL_PATH: ${{ github.workspace }}
    MAIN_BRANCH: "production"
    PRIVATE_BRANCH: ${{ github.repository }}
    SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Odoo CICD executor
              uses: actions/checkout@v4
              with:
                  repository: ${{ env.REPO }}
                  ssh-key: ${{ env.SSH_KEY }}
                  path: ${{ env.LOCAL_PATH }}
                  ref: ${{ env.PRIVATE_BRANCH }}
                  fetch-depth: 1

            - name: Update file for commit
              run: |
                  sed -i '1s/^/[PR #${{github.event.pull_request.number}}](${{github.event.pull_request.html_url}})\n/' ${{github.workspace}}/.github/trigger-commit.txt

            - name: Push commit to trigger CICD - Test workflow
              uses: cpina/github-action-push-to-another-repository@main
              env:
                  SSH_DEPLOY_KEY: ${{ env.SSH_KEY }}
              with:
                  source-directory: ./
                  destination-github-username: "xmars4"
                  destination-repository-name: "odoo-cicd-executor"
                  user-email: "truong@vdx.vn"
                  commit-message: test
                  target-branch: ${{ env.PRIVATE_BRANCH }}
    deploy:
        runs-on: ubuntu-latest
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        steps:
            - name: Checkout Odoo CICD executor
              uses: actions/checkout@v4
              with:
                  repository: ${{ env.EXECUTOR_REPO }}
                  token: ${{ env.ACCESS_TOKEN }}
                  path: ${{ env.EXECUTOR_LOCAL_PATH }}
                  ref: ${{ env.MAIN_BRANCH }}
                  fetch-depth: 1

            - name: Update file for commit
              run: |
                  sed -i '1s/^/[PR #${{github.event.pull_request.number}}](${{github.event.pull_request.html_url}})\n/' ${{github.workspace}}/.github/trigger-commit.txt

            - name: Push commit to trigger CICD - Deploy workflow
              uses: cpina/github-action-push-to-another-repository@main
              env:
                  SSH_DEPLOY_KEY: ${{ env.SSH_KEY }}
              with:
                  source-directory: ./
                  destination-github-username: "xmars4"
                  destination-repository-name: "odoo-cicd-executor"
                  user-email: "truong@vdx.vn"
                  commit-message: deploy
                  target-branch: ${{ env.PRIVATE_BRANCH }}
