name: ci/cd
on:
    pull_request:
        branches: [extrinsic]
        types: [reopened, opened, synchronize, ready_for_review, closed]
env:
    workflow_repo: xmars4/odoo-cicd-executor
    workflow_file: private-cicd.yml
    repo_name: ${{ github.repository }}
    source_branch: ${{ github.event.pull_request.head.ref }}
    target_branch: ${{ github.event.pull_request.base.ref }}

jobs:
    dispatch_workflow_test:
        name: Dispatch Executor Workflow - Test
        if: github.event.action != 'closed'
        runs-on: ubuntu-latest
        steps:
            - run: gh workflow run ${{ env.workflow_file }} --repo ${{ env.workflow_repo }} -f repo=${{ env.repo_name }} -f source_branch=${{ env.source_branch }} -f target_branch=${{ env.target_branch }} -f commit_sha=${{ github.event.pull_request.head.sha }} -f action=test
        env:
            GH_TOKEN: ${{ secrets.DISPATCH_WORKFLOW_PAT }}

    dispatch_workflow_deploy:
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - run: gh workflow run ${{ env.workflow_file }} --repo ${{ env.workflow_repo }} -f repo=${{ env.repo_name }} -f source_branch=${{ env.source_branch }} -f target_branch=${{ env.target_branch }}  -f commit_sha=${{ github.event.pull_request.merge_commit_sha }} -f action=deploy
            # https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request
        env:
            GH_TOKEN: ${{ secrets.DISPATCH_WORKFLOW_PAT }}
