name: ci/cd
on:
    workflow_call:
        inputs:
            commit_message:
                required: true
                type: string

env:
    # cicd executor repo info
    REPO: "xmars4/odoo-cicd-executor"
    LOCAL_PATH: ${{ github.workspace }}/executor
    MAIN_BRANCH: "production"
    # this branch matches the Odoo repo name
    PRIVATE_BRANCH: ${{ github.repository }}
    SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
    commit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Odoo CICD executor
              uses: actions/checkout@v4
              with:
                  repository: xmars4/odoo-cicd-executor
                  ssh-key: ${{ env.SSH_KEY }}
                  path: ${{ env.LOCAL_PATH }}
                  ref: ${{ env.PRIVATE_BRANCH }}
                  fetch-depth: 1
                  ssh-strict: false

            - name: Update file for commit
              run: |
                  sed -i 's@<private_repo_path>@${{ github.repository }}@g' "${{github.workspace}}/.github/workflows/private-cicd.yml"
                  trigger_commit_file="${{github.workspace}}/.github/trigger-commit.md"
                  timestamp=$(date '+%Y-%m-%d %H:%M:%S')
                  echo -e "[PR #${{github.event.pull_request.number}}_${timestamp}](${{github.event.pull_request.html_url}})\n" | cat - ${trigger_commit_file} > temp && mv temp ${trigger_commit_file}

            - name: Push commit to trigger CICD - Test workflow
              uses: cpina/github-action-push-to-another-repository@main
              env:
                  SSH_DEPLOY_KEY: ${{ env.SSH_KEY }}
              with:
                  source-directory: ./
                  destination-github-username: "xmars4"
                  destination-repository-name: "odoo-cicd-executor"
                  user-email: "truong@vdx.vn"
                  commit-message: ${{inputs.commit_message}}
                  target-branch: ${{ env.PRIVATE_BRANCH }}
